baseURL: "https://go.szostok.io"
languageCode: "en-us"
title: "go.szostok.io"
theme: "go-vanity"

copyright: "Copyright © 2022 Mateusz Szostok (mateusz@szostok.io); all rights reserved."
paginate: 5
params:
  redirect = true
